# Generated by Django 4.0.1 on 2022-02-08 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=127, null=True)),
                ('value', models.CharField(blank=True, max_length=127, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='date logged')),
                ('serial', models.CharField(blank=True, max_length=30, null=True)),
                ('assetTag', models.CharField(blank=True, max_length=30, null=True)),
                ('customer', models.CharField(max_length=30, null=True)),
                ('claim', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, choices=[('New', 'New'), ('Ordered', 'Ordered'), ('Repaired', 'Repaired'), ('Finished', 'Finished')], default='New', max_length=90, null=True)),
                ('model', models.CharField(blank=True, choices=[('Dell 3100 (Touch, +USB)', 'Dell 3100 (Touch, +USB)'), ('Dell 3100 (Non touch, +USB)', 'Dell 3100 (Non touch, +USB)'), ('Dell 3100 (Non touch, no extra ports)', 'Dell 3100 (Non touch, no extra ports)'), ('Asus C214M', 'Asus C214M'), ('HP 11 G4 EE', 'HP 11 G4 EE'), ('HP 11 G5 EE', 'HP 11 G5 EE'), ('HP 11 G6 EE', 'HP 11 G6 EE'), ('HP 11 G7 EE', 'HP 11 G7 EE'), ('HP 11a G8 EE', 'HP 11a G8 EE'), ('Lenovo 500e 81ES', 'Lenovo 500e 81ES'), ('Lenovo 500e (2nd Gen) 81MC', 'Lenovo 500e (2nd Gen) 81MC'), ('Samsung Chromebook 4 (xe310xba)', 'Samsung Chromebook 4 (xe310xba)')], max_length=90, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('cost', models.FloatField(max_length=12, null=True)),
                ('ordered', models.BooleanField(default=False)),
                ('replaced', models.BooleanField(default=False)),
                ('mpn', models.CharField(max_length=24, null=True)),
                ('sku', models.CharField(max_length=24, null=True)),
                ('reason', models.CharField(max_length=127, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nobility.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nobility.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
