# Generated by Django 4.0.1 on 2022-02-08 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nobility', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='assetTag',
            new_name='asset',
        ),
    ]
