devices = [
    ("Dell 3100 (Touch, +USB)", "Dell 3100 (Touch, +USB)"),
    ("Dell 3100 (Non touch, +USB)", "Dell 3100 (Non touch, +USB)"),
    ("Dell 3100 (Non touch, no extra ports)", "Dell 3100 (Non touch, no extra ports)"),
    ("Asus C214M", "Asus C214M"),
    ("HP 11 G4 EE", "HP 11 G4 EE"),
    ("HP 11 G5 EE", "HP 11 G5 EE"),
    ("HP 11 G6 EE", "HP 11 G6 EE"),
    ("HP 11 G7 EE", "HP 11 G7 EE"),
    ("HP 11a G8 EE", "HP 11a G8 EE"),
    ("Lenovo 500e 81ES", "Lenovo 500e 81ES"),
    ("Lenovo 500e (2nd Gen) 81MC", "Lenovo 500e (2nd Gen) 81MC"),
    ("Samsung Chromebook 4 (xe310xba)", "Samsung Chromebook 4 (xe310xba)"),
]

parts = {
    "Dell 3100 (Touch, +USB)": [
        {
            "name": "LCD Back Cover",
            "sku": "BAC-SNG-9257-2",
            "mpn": "034YFY",
            "price": 39.99,
        },
        {
            "name": "Battery (Long cable version)",
            "sku": "BAT-SNG-4163-5",
            "mpn": "51KD7",
            "price": 59.99,
        },
        {
            "name": "Bezel",
            "sku": "BEZ-SNG-7496-2",
            "mpn": "06C2J6",
            "price": 34.99,
        },
        {
            "name": "Bottom Cover",
            "sku": "BOT-SNG-6092-2",
            "mpn": "02RY30",
            "price": 34.99,
        },
        {
            "name": "Camera Board",
            "sku": "CAM-SNG-4538-2",
            "mpn": "0G4JK9",
            "price": 19.99,
        },
        {
            "name": "LCD and Camera Cable",
            "sku": "CBL-LCD-3713-1",
            "mpn": "0TWY13",
            "price": 19.99,
        },
        {
            "name": "Power and USB Daughterboard",
            "sku": "DAU-SNG-4962-1",
            "mpn": "0G61M2",
            "price": 29.99,
        },
        {
            "name": "Hinge Set",
            "sku": "HNG-SET-8480-2",
            "mpn": "0R5KHK",
            "price": 29.99,
        },
        {
            "name": "Palmrest Assembly",
            "sku": "PLM-ASY-1605-1",
            "mpn": "0TK87M",
            "price": 89.99,
        },
        {
            "name": "Speaker Set",
            "sku": "SPK-SET-3803-2",
            "mpn": "0MFX68",
            "price": 4.99,
        },
        {
            "name": "Touchpad",
            "sku": "TPD-SNG-7201-2",
            "mpn": "0RJR6J",
            "price": 24.99,
        },
        {
            "name": "Keyboard",
            "sku": "KYB-SNG-6044-2",
            "mpn": "00D2DT",
            "price": 39.99,
        },
        {
            "name": "Palmrest (No keyboard or touchpad)",
            "sku": "PLM-ASY-331-1",
            "mpn": "034Y6Y",
            "price": 24.99,
        },
        {
            "name": "LCD Touch Panel, 40-Pin",
            "sku": "LCD-SNG-9495-5",
            "mpn": "B116XAK01.2",
            "price": 109.99,
        },
        {
            "name": "Dell 11 3100 Touch/Non-Touch Chromebook Battery (Short cable version)",
            "sku": "BAT-SNG-8886-1",
            "mpn": "JPFMR/07T0D3",
            "price": 63.99,
        },
        {
            "name": "Motherboard, 4GB",
            "sku": "MOT-SNG-9454-2",
            "mpn": "0W1C7C",
            "price": 199.99,
        },
    ],
    "HP 11 G5 EE": [
        {
            "name": "LCD Back Cover",
            "sku": "BAC-SNG-3318-1",
            "mpn": "917426-001",
            "price": 39.99,
        },
        {
            "name": "Battery - 918669-855",
            "sku": "BAT-SNG-6841-1",
            "mpn": "918669-855",
            "price": 49.99,
        },
        {
            "name": "Bezel",
            "sku": "BEZ-SNG-7822-1",
            "mpn": "917430-001",
            "price": 29.99,
        },
        {
            "name": "Bottom Cover",
            "sku": "BOT-SNG-6559-1",
            "mpn": "917428-001",
            "price": 29.99,
        },
        {
            "name": "USB Daughterboard",
            "sku": "DAU-SNG-7488-1",
            "mpn": "917436-001",
            "price": 9.99,
        },
        {
            "name": "DC In-Jack",
            "sku": "DCJ-SNG-2486-1",
            "mpn": "920842-001",
            "price": 9.99,
        },
        {
            "name": "Hinge Set",
            "sku": "HNG-SET-6189-1",
            "mpn": "917434-001",
            "price": 11.99,
        },
        {
            "name": "Motherboard, 4GB",
            "sku": "MOT-SNG-9776-1",
            "mpn": "917495-001",
            "price": 69.99,
        },
        {
            "name": "Palmrest Assembly w/ Keyboard Only",
            "sku": "PLM-ASY-6433-1",
            "mpn": "917442-001",
            "price": 49.99,
        },
        {
            "name": "Speaker Set",
            "sku": "SPK-SET-1987-1",
            "mpn": "917440-001",
            "price": 9.99,
        },
        {
            "name": "Touchpad",
            "sku": "TPD-SNG-3187-1",
            "mpn": "917437-001",
            "price": 27.99,
        },
        {
            "name": "Wifi Card",
            "sku": "WIF-SNG-421-6",
            "mpn": "860883-001",
            "price": 9.99,
        },
        {
            "name": "Motherboard, 2GB",
            "sku": "MOT-SNG-5438-1",
            "mpn": "917494-001",
            "price": 139.99,
        },
        {
            "name": "LCD Cable, Touch",
            "sku": "CBL-LCD-4902-1",
            "mpn": "919097-001",
            "price": 9.99,
        },
        {
            "name": "LCD Cable",
            "sku": "CBL-LCD-8122-1",
            "mpn": "917431-001",
            "price": 9.99,
        },
        {
            "name": "Camera Board",
            "sku": "CAM-SNG-5625-1",
            "mpn": "922797-001",
            "price": 19.99,
        },
    ],
    "Generic": [
        {"name": "LCD Back Cover", "sku": "", "mpn": "", "price": None},
        {"name": "Battery", "sku": "", "mpn": "", "price": None},
        {"name": "Bezel", "sku": "", "mpn": "", "price": None},
        {"name": "Bottom Cover", "sku": "", "mpn": "", "price": None},
        {"name": "USB Daughterboard", "sku": "", "mpn": "", "price": None},
        {"name": "DC In-Jack", "sku": "", "mpn": "", "price": None},
        {"name": "Hinge Set", "sku": "", "mpn": "", "price": None},
        {"name": "Motherboard, 4GB", "sku": "", "mpn": "", "price": None},
        {
            "name": "Palmrest Assembly w/ Keyboard Only",
            "sku": "",
            "mpn": "",
            "price": None,
        },
        {"name": "Speaker Set", "sku": "", "mpn": "", "price": None},
        {"name": "Touchpad", "sku": "", "mpn": "", "price": None},
        {"name": "Wifi Card", "sku": "", "mpn": "", "price": None},
        {"name": "Motherboard, 2GB", "sku": "", "mpn": "", "price": None},
        {"name": "LCD Cable, Touch-Version, 30-Pin", "sku": "", "mpn": "", "price": None},
        {"name": "LCD Cable", "sku": "", "mpn": "", "price": None},
        {"name": "Camera Board", "sku": "", "mpn": "", "price": None},
    ],
}
